spring.application.name=trashsorting

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/mrf-db
spring.datasource.username=root
spring.datasource.password=ishuraja24@2007